### ISSUE TITLE
Order independent collection? 

### ISSUE THREAD

**Issue by Jack-Works** [tc39/proposal-record-tuple#204]
Like tuple or Set, but when comparing, the order is independent.

**Comment by iwikal** [comment]
Sounds useful, but it seems out of scope of this proposal. It could be a follow-up.

**Comment by ljharb** [comment]
How could order be independent if there’s an observable iteration order?

**Comment by Jack-Works** [comment]
Sort them?

**Comment by iwikal** [comment]
Sorting things in an observable implementation-defined order might be undesirable (though not unprecedented). One solution could be to hide the order by making them non-iterable, like `WeakSet`, but then you can pretty much only use them to check for equality, or whether they contain a specific thing or subset of things. Another option is to preserve original order, but ignore it in equality comparisons.

**Comment by iwikal** [comment]
One possible workaround might be to use a record for this purpose. Simply use your values as keys, mapping to some predetermined value, such as `true`. Note that this will be non-iterable, like `WeakSet`.
```js
function orderIndependentCollection(values) {
  return Record.fromEntries(function *() {
    for (const value of values) yield [value, true]
  }())
}
```

**Comment by Jamesernator** [comment]
> If your values are strings, one possible workaround might be to use a record for this purpose. Simply use your strings as keys, mapping to some predetermined value, such as `true`.

Even without strings, you can simply map all objects to an arbitrary consistent id number and sort based on that e.g.:

```js
let currentId = 0;
const objectIds = new WeakMap();

export default function keyFromUnsorted(values) {
  return Tuple(...values).sorted((a, b) => {
    if (objectIds.has(a)) objectIds.set(a, currentId++);
    if (objectIds.has(b)) objectIds.set(b, currentId++);
    return objectIds.get(a) - objectIds.get(b);
  });
}
```

If you wanna mix objects and primitives arbitrarily, the logic is more tedious, but basically you can just sort first by `typeof` then by value.

The only real problem is if you're dealing with symbols, as like objects you need to associate them with an ID, but you can't use a `WeakMap` ([although there is talk about allowing it](https://github.com/tc39/proposal-symbols-as-weakmap-keys)) so they'll never be garbage collected. If that's the case, you need yet another level of indirection where you map every symbol to a weakref to a object, *and then* get ids of those objects to sort by.

Admittedly for the most general case of supporting all values (primitive or object), this is actually kinda difficult, but in practice I think the overwhelming majority of use cases for such a collection is where types of each value are the same.

**Comment by rricard** [comment]
This sounds like this is a subject on its own. I don't think we want to cover this as part of R&T but we definitely can imagine future data structures compatible with R&T that would behave like so.
