### ISSUE TITLE
We need Object.toImmutable

### ISSUE THREAD

**Issue by lygstate** [tc39/proposal-record-tuple#221]
This resolved:
https://es.discourse.group/t/object-deepfreeze/652/6

**Comment by ljharb** [comment]
We definitely do not ever need anything new on Object.prototype ever again; separately, this solution wouldn’t work for `Object.create(null)`, and it would make no sense to call it on all the other things that inherit from Object.prototype: boolean, numbers, bigints, symbols, strings, functions, regexes, Dates, and even records and tuples themselves.

A static method, on Record and Tuple, would be more appropriate.

**Comment by lygstate** [comment]
> We definitely do not ever need anything new on Object.prototype ever again; separately, this solution wouldn’t work for `Object.create(null)`, and it would make no sense to call it on all the other things that inherit from Object.prototype: boolean, numbers, bigints, symbols, strings, functions, regexes, Dates, and even records and tuples themselves.
> 
> A static method, on Record and Tuple, would be more appropriate.

So Object.toImmutable? As Tuple/Reocrd are two class, which one to use?

**Comment by ljharb** [comment]
One on each, presumably. I might want a record from an array, or a tuple from an arraylike object. It wouldn’t make sense on Object.

**Comment by lygstate** [comment]
> One on each, presumably. I might want a record from an array, or a tuple from an arraylike object. It wouldn’t make sense on Object.

Weird for the user, too complicated, `simple is good`. If you wanna special things, we always can writing code do that.
In normal case, Array Object always to [], and other Objects to {}.

**Comment by Jack-Works** [comment]
Yeah, a Symbol will be cool, but not O.prototype

**Comment by ljharb** [comment]
Being on Object isn’t simple, that’s the problem, because it’s too broad.

**Comment by lygstate** [comment]
> Yeah, a Symbol will be cool, but not O.prototype

Please be moe specfic? Symbol.toImmutable ?

**Comment by Jack-Works** [comment]
Oh, I thought you're talking about the protocol of converting objects to records/tuples. That isn't the case so please ignore what I said

**Comment by rricard** [comment]
We are voluntarily avoiding to define any _deep_ transformations of objects/arrays to Record/Tuple structures as part of this proposal: it can be done by defining your own `toImmutable` function in userland by using `Record.fromEntries(...)` and `Tuple(...)` or it can eventually be proposed as a follow-on proposal later.

As highlighted by @ljharb, we also don't want to alter `Object.prototype` as well so any API that we might add later would be on the `Record` or `Tuple` objects.

Related to that discourse thread, we should try to look at getting Records/Tuples straight out of the import in my opinion instead of converting them after the fact. I have no intention in suggesting a change of the current state of JSON modules but I am trying to think about ways of layering that feature on top of it.

I will close this issue and open another issue to discuss that more precise subject.

**Comment by rricard** [comment]
I am going to close that issue as it is a non-goal for us mainly because we want to discourage linear-time copying idioms. If you got objects, you should use them as-is; trying to make them Record/Tuple will incur a cost that we do not want to encourage you to pay.
